name: react-advanced-2022
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  react-advanced-2022-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:

      - uses: actions/checkout@v2

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: install npm
        run: npm install

      - name: eslint for typescript
        run: npm run eslint-ts

      - name: eslint for css
        run: npm run eslint-scss

      - name: unit testing
        run: npm run test-unit

      - name: project production build
        run: npm run build-prod
